server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-payment
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  application:
    name: ms-payments

  jpa:
    hibernate:
     ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


client:
  ms-country:
    endpoint: http://localhost:8081


